# -*- coding: utf-8 -*-
"""pandas_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1Bgd4B1sqFVqx_IPbSHeTXkK6QZlN-e
"""

import pandas as pd
from google.colab import files
uploaded=files.upload()

import io
df=pd.read_csv(io.BytesIO(uploaded['nba.csv']))
print(df)

#printing columns
for col in df.columns:
    print(col,sep=" ")

#set a col as index
df.set_index('Name',inplace=True)
print("\n",df)
#reset col with index
df.reset_index(inplace=True)
print(df)

#multiindex
df.set_index(['Name','Team'],inplace=True)
print(df)

#Transpose
print(df.transpose())